name: Sync Upstream
on:
  schedule:
  - cron: "0 12 * * 6"  # run once a week, 12:00 every Saturday
  workflow_dispatch:    # run manually

jobs:
  # just sync to upstream in master branch
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master       # set the branch to merge to
          fetch-depth: 0
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: ACL4SSR/ACL4SSR   # set the upstream repo
          upstream-branch: master     # set the upstream branch to merge from
          branch: master              # set the branch to merge to

  # sync to upstream with custom modification in custom branch
  rebase-upstream:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: custom     # the branch to do rebase
        fetch-depth: 0  # greater than the number of commits you made
    - name: Rebase Upstream
      uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: ACL4SSR/ACL4SSR   # the upstream repo
        branch: master              # the upstream branch that is rebased on
        depth: 0                    # greater than the number of commits the upstream made in a period