name: Rebase Upstream
on:
  schedule:
  - cron: "0 12 * * 6"  # run once a week, 12:00 every Saturday
  workflow_dispatch:   # run manually

jobs:
  # just sync to upstream in master branch
  sync-master:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master     # the branch to do rebase
        fetch-depth: 0  # greater than the number of commits you made
    - name: Rebase Upstream
      uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: ACL4SSR/ACL4SSR   # the upstream repo
        branch:   master            # the upstream branch that is rebased on
        depth: 0                    # greater than the number of commits the upstream made in a period

  # sync to upstream with custom modification in custom branch
  rebase-custom:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: custom     # the branch to do rebase
        fetch-depth: 0  # greater than the number of commits you made
    - name: Rebase Upstream
      uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: ACL4SSR/ACL4SSR   # the upstream repo
        branch:   master            # the upstream branch that is rebased on
        depth: 0                    # greater than the number of commits the upstream made in a period